[package]
name = "local"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
directories = "6.0.0"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time"] }
turso = "=0.7.2"
zygo-core = { path = "../core" }
