[package]
name = "local"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
directories = "6.0.0"
serde_json = { workspace = true }
tokio = { workspace = true }
turso = "0.7.2"
zygo-core = { path = "../core" }
