# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import orchestrator_pb2 as orchestrator__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orchestrator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorkflow = channel.unary_unary(
                '/orchestrator.v1.OrchestratorService/RegisterWorkflow',
                request_serializer=orchestrator__pb2.RegisterWorkflowRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.RegisterWorkflowResponse.FromString,
                _registered_method=True)
        self.HandleJobRunEvent = channel.unary_unary(
                '/orchestrator.v1.OrchestratorService/HandleJobRunEvent',
                request_serializer=orchestrator__pb2.HandleJobRunEventRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.HandleJobRunEventResponse.FromString,
                _registered_method=True)
        self.GetWorkflowVersionSchema = channel.unary_unary(
                '/orchestrator.v1.OrchestratorService/GetWorkflowVersionSchema',
                request_serializer=orchestrator__pb2.GetWorkflowVersionSchemaRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.GetWorkflowVersionSchemaResponse.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/orchestrator.v1.OrchestratorService/ListRuns',
                request_serializer=orchestrator__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.ListRunsResponse.FromString,
                _registered_method=True)
        self.ListRunEvents = channel.unary_unary(
                '/orchestrator.v1.OrchestratorService/ListRunEvents',
                request_serializer=orchestrator__pb2.ListRunEventsRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.ListRunEventsResponse.FromString,
                _registered_method=True)
        self.ListWorkflows = channel.unary_unary(
                '/orchestrator.v1.OrchestratorService/ListWorkflows',
                request_serializer=orchestrator__pb2.ListWorkflowsRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.ListWorkflowsResponse.FromString,
                _registered_method=True)
        self.Livestream = channel.unary_unary(
                '/orchestrator.v1.OrchestratorService/Livestream',
                request_serializer=orchestrator__pb2.LivestreamRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.LivestreamResponse.FromString,
                _registered_method=True)


class OrchestratorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterWorkflow(self, request, context):
        """Mutative RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleJobRunEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflowVersionSchema(self, request, context):
        """Query RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkflows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Livestream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorkflow,
                    request_deserializer=orchestrator__pb2.RegisterWorkflowRequest.FromString,
                    response_serializer=orchestrator__pb2.RegisterWorkflowResponse.SerializeToString,
            ),
            'HandleJobRunEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleJobRunEvent,
                    request_deserializer=orchestrator__pb2.HandleJobRunEventRequest.FromString,
                    response_serializer=orchestrator__pb2.HandleJobRunEventResponse.SerializeToString,
            ),
            'GetWorkflowVersionSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflowVersionSchema,
                    request_deserializer=orchestrator__pb2.GetWorkflowVersionSchemaRequest.FromString,
                    response_serializer=orchestrator__pb2.GetWorkflowVersionSchemaResponse.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=orchestrator__pb2.ListRunsRequest.FromString,
                    response_serializer=orchestrator__pb2.ListRunsResponse.SerializeToString,
            ),
            'ListRunEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunEvents,
                    request_deserializer=orchestrator__pb2.ListRunEventsRequest.FromString,
                    response_serializer=orchestrator__pb2.ListRunEventsResponse.SerializeToString,
            ),
            'ListWorkflows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkflows,
                    request_deserializer=orchestrator__pb2.ListWorkflowsRequest.FromString,
                    response_serializer=orchestrator__pb2.ListWorkflowsResponse.SerializeToString,
            ),
            'Livestream': grpc.unary_unary_rpc_method_handler(
                    servicer.Livestream,
                    request_deserializer=orchestrator__pb2.LivestreamRequest.FromString,
                    response_serializer=orchestrator__pb2.LivestreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator.v1.OrchestratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orchestrator.v1.OrchestratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.v1.OrchestratorService/RegisterWorkflow',
            orchestrator__pb2.RegisterWorkflowRequest.SerializeToString,
            orchestrator__pb2.RegisterWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleJobRunEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.v1.OrchestratorService/HandleJobRunEvent',
            orchestrator__pb2.HandleJobRunEventRequest.SerializeToString,
            orchestrator__pb2.HandleJobRunEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflowVersionSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.v1.OrchestratorService/GetWorkflowVersionSchema',
            orchestrator__pb2.GetWorkflowVersionSchemaRequest.SerializeToString,
            orchestrator__pb2.GetWorkflowVersionSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.v1.OrchestratorService/ListRuns',
            orchestrator__pb2.ListRunsRequest.SerializeToString,
            orchestrator__pb2.ListRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRunEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.v1.OrchestratorService/ListRunEvents',
            orchestrator__pb2.ListRunEventsRequest.SerializeToString,
            orchestrator__pb2.ListRunEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkflows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.v1.OrchestratorService/ListWorkflows',
            orchestrator__pb2.ListWorkflowsRequest.SerializeToString,
            orchestrator__pb2.ListWorkflowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Livestream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.v1.OrchestratorService/Livestream',
            orchestrator__pb2.LivestreamRequest.SerializeToString,
            orchestrator__pb2.LivestreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
