"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
from . import orchestrator_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class OrchestratorServiceStub:
    @typing.overload
    def __new__(cls, channel: grpc.Channel) -> OrchestratorServiceStub: ...
    @typing.overload
    def __new__(cls, channel: grpc.aio.Channel) -> OrchestratorServiceAsyncStub: ...
    RegisterWorkflow: grpc.UnaryUnaryMultiCallable[orchestrator_pb2.RegisterWorkflowRequest, orchestrator_pb2.RegisterWorkflowResponse]
    """Mutative RPCs"""
    HandleJobRunEvent: grpc.UnaryUnaryMultiCallable[orchestrator_pb2.HandleJobRunEventRequest, orchestrator_pb2.HandleJobRunEventResponse]
    GetWorkflowVersionSchema: grpc.UnaryUnaryMultiCallable[orchestrator_pb2.GetWorkflowVersionSchemaRequest, orchestrator_pb2.GetWorkflowVersionSchemaResponse]
    """Query RPCs"""
    ListRuns: grpc.UnaryUnaryMultiCallable[orchestrator_pb2.ListRunsRequest, orchestrator_pb2.ListRunsResponse]
    ListRunEvents: grpc.UnaryUnaryMultiCallable[orchestrator_pb2.ListRunEventsRequest, orchestrator_pb2.ListRunEventsResponse]
    ListWorkflows: grpc.UnaryUnaryMultiCallable[orchestrator_pb2.ListWorkflowsRequest, orchestrator_pb2.ListWorkflowsResponse]
    Livestream: grpc.UnaryUnaryMultiCallable[orchestrator_pb2.LivestreamRequest, orchestrator_pb2.LivestreamResponse]

@typing.type_check_only
class OrchestratorServiceAsyncStub(OrchestratorServiceStub):
    def __init__(self, channel: grpc.aio.Channel) -> None: ...
    RegisterWorkflow: grpc.aio.UnaryUnaryMultiCallable[orchestrator_pb2.RegisterWorkflowRequest, orchestrator_pb2.RegisterWorkflowResponse]  # type: ignore[assignment]
    """Mutative RPCs"""
    HandleJobRunEvent: grpc.aio.UnaryUnaryMultiCallable[orchestrator_pb2.HandleJobRunEventRequest, orchestrator_pb2.HandleJobRunEventResponse]  # type: ignore[assignment]
    GetWorkflowVersionSchema: grpc.aio.UnaryUnaryMultiCallable[orchestrator_pb2.GetWorkflowVersionSchemaRequest, orchestrator_pb2.GetWorkflowVersionSchemaResponse]  # type: ignore[assignment]
    """Query RPCs"""
    ListRuns: grpc.aio.UnaryUnaryMultiCallable[orchestrator_pb2.ListRunsRequest, orchestrator_pb2.ListRunsResponse]  # type: ignore[assignment]
    ListRunEvents: grpc.aio.UnaryUnaryMultiCallable[orchestrator_pb2.ListRunEventsRequest, orchestrator_pb2.ListRunEventsResponse]  # type: ignore[assignment]
    ListWorkflows: grpc.aio.UnaryUnaryMultiCallable[orchestrator_pb2.ListWorkflowsRequest, orchestrator_pb2.ListWorkflowsResponse]  # type: ignore[assignment]
    Livestream: grpc.aio.UnaryUnaryMultiCallable[orchestrator_pb2.LivestreamRequest, orchestrator_pb2.LivestreamResponse]  # type: ignore[assignment]

class OrchestratorServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def RegisterWorkflow(
        self,
        request: orchestrator_pb2.RegisterWorkflowRequest,
        context: _ServicerContext,
    ) -> typing.Union[orchestrator_pb2.RegisterWorkflowResponse, collections.abc.Awaitable[orchestrator_pb2.RegisterWorkflowResponse]]:
        """Mutative RPCs"""

    @abc.abstractmethod
    def HandleJobRunEvent(
        self,
        request: orchestrator_pb2.HandleJobRunEventRequest,
        context: _ServicerContext,
    ) -> typing.Union[orchestrator_pb2.HandleJobRunEventResponse, collections.abc.Awaitable[orchestrator_pb2.HandleJobRunEventResponse]]: ...

    @abc.abstractmethod
    def GetWorkflowVersionSchema(
        self,
        request: orchestrator_pb2.GetWorkflowVersionSchemaRequest,
        context: _ServicerContext,
    ) -> typing.Union[orchestrator_pb2.GetWorkflowVersionSchemaResponse, collections.abc.Awaitable[orchestrator_pb2.GetWorkflowVersionSchemaResponse]]:
        """Query RPCs"""

    @abc.abstractmethod
    def ListRuns(
        self,
        request: orchestrator_pb2.ListRunsRequest,
        context: _ServicerContext,
    ) -> typing.Union[orchestrator_pb2.ListRunsResponse, collections.abc.Awaitable[orchestrator_pb2.ListRunsResponse]]: ...

    @abc.abstractmethod
    def ListRunEvents(
        self,
        request: orchestrator_pb2.ListRunEventsRequest,
        context: _ServicerContext,
    ) -> typing.Union[orchestrator_pb2.ListRunEventsResponse, collections.abc.Awaitable[orchestrator_pb2.ListRunEventsResponse]]: ...

    @abc.abstractmethod
    def ListWorkflows(
        self,
        request: orchestrator_pb2.ListWorkflowsRequest,
        context: _ServicerContext,
    ) -> typing.Union[orchestrator_pb2.ListWorkflowsResponse, collections.abc.Awaitable[orchestrator_pb2.ListWorkflowsResponse]]: ...

    @abc.abstractmethod
    def Livestream(
        self,
        request: orchestrator_pb2.LivestreamRequest,
        context: _ServicerContext,
    ) -> typing.Union[orchestrator_pb2.LivestreamResponse, collections.abc.Awaitable[orchestrator_pb2.LivestreamResponse]]: ...

def add_OrchestratorServiceServicer_to_server(servicer: OrchestratorServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
