# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal


@dataclass
class StoreConfig:
    root_uri: str
    kwargs: dict[str, Any] | None = field(default_factory=dict)


@dataclass
class HttpConfig:
    url: str
    headers: dict[str, str] | None = field(default_factory=dict)
    timeout: float | None = 30.0
    max_retries: int | None = 3
    retry_interval: float | None = 5.0


@dataclass
class DataReferenceInserted:
    type: Literal["data_reference_inserted"]
    data_reference: str


@dataclass
class ChannelItemInserted:
    type: Literal["channel_item_inserted"]
    channel_id: str
    data_reference: str


@dataclass
class TagInserted:
    type: Literal["tag_inserted"]
    value: str
    data_reference: str | None = None


@dataclass
class WorkflowGetMetadataCommand:
    command: Literal["workflow_get_metadata"]
    target: str


@dataclass
class JobRunArgs:
    job_id: str
    data_reference_uri: str
    workflow_run_id: str
    job_run_id: str


@dataclass
class JobMetadata:
    id: str
    content_hash: str
    input_channel_id: str
    output_channel_id: str


@dataclass
class ChannelMetadata:
    id: str
    accepted_file_extensions: list[str]


@dataclass
class ModelTrainCommand:
    command: Literal["model_train"]
    target: str
    dataset_config: StoreConfig
    store_config: StoreConfig
    params: dict[str, Any] | None = None
    http_config: HttpConfig | None = None


@dataclass
class WorkflowRunJobCommand:
    command: Literal["workflow_run_job"]
    target: str
    args: JobRunArgs
    job_store_config: StoreConfig | None = None
    workflow_store_config: StoreConfig | None = None
    cache_store_config: StoreConfig | None = None
    http_config: HttpConfig | None = None


type IpcMessage = DataReferenceInserted | ChannelItemInserted | TagInserted


@dataclass
class WorkflowGetMetadataOutput:
    id: str
    content_hash: str
    input_channel_id: str
    output_channel_id: str
    jobs: list[JobMetadata]
    channels: list[ChannelMetadata]


type CliOutput = WorkflowGetMetadataOutput


type CliCommand = WorkflowRunJobCommand | WorkflowGetMetadataCommand | ModelTrainCommand


@dataclass
class HttpIPCMessage:
    id: str
    messages: list[IpcMessage]


type CliPayload = CliCommand | CliOutput
