# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal


@dataclass
class ChannelMetadata:
    id: str
    accepted_file_extensions: list[str]


@dataclass
class JobMetadata:
    id: str
    content_hash: str
    input_channel_id: str
    output_channel_id: str


@dataclass
class WorkflowMetadata:
    id: str
    content_hash: str
    input_channel_id: str
    output_channel_id: str
    jobs: list[JobMetadata]
    channels: list[ChannelMetadata]


@dataclass
class JobRunArgs:
    job_id: str
    data_reference_uri: str
    workflow_run_id: str
    job_run_id: str


@dataclass
class StoreConfig:
    root_uri: str
    kwargs: dict[str, str] | None = field(default_factory=dict)


@dataclass
class HttpConfig:
    url: str
    headers: dict[str, str] | None = field(default_factory=dict)
    timeout: float | None = 30.0
    max_retries: int | None = 3
    retry_interval: float | None = 5.0


@dataclass
class DataReferenceCreated:
    type: Literal["data_reference_created"]
    data_reference: str


@dataclass
class ChannelItemInserted:
    type: Literal["channel_item_inserted"]
    channel_id: str
    data_reference: str


@dataclass
class TagInserted:
    type: Literal["tag_inserted"]
    value: str
    data_reference: str | None = None


@dataclass
class JobStarted:
    type: Literal["job_started"]
    job_run_id: str


@dataclass
class JobSucceeded:
    type: Literal["job_succeeded"]
    job_run_id: str


@dataclass
class JobFailed:
    type: Literal["job_failed"]
    job_run_id: str
    error: str


type IpcMessage = (
    DataReferenceCreated
    | ChannelItemInserted
    | TagInserted
    | JobStarted
    | JobSucceeded
    | JobFailed
)


@dataclass
class HttpIPCMessage:
    id: str
    workflow_run_id: str
    job_run_id: str
    messages: list[IpcMessage]


type ZygoProviderProtocolV0Payload = (
    WorkflowMetadata
    | JobRunArgs
    | StoreConfig
    | HttpConfig
    | IpcMessage
    | HttpIPCMessage
)
