//! Generation of [`JobEntrypoint`]s: how a job is actually executed.
//!
//! An entrypoint is either a local process (`cwd` + `exec`) or a remote
//! invocation (`url` + headers). Which variant is produced is *not* a per-job
//! coin flip: the orchestrator requires every job in a workflow to match its
//! [`OrchestratorMode`] (all local, or all remote). The desired mode is
//! therefore supplied by the parent as the generation context, and this
//! generator only varies the concrete values within that mode.
//!
//! # Local jobs talk back to the orchestrator
//!
//! A generated world is only interesting if running it actually *drives the
//! orchestrator*. A bare `echo`/`true` entrypoint does nothing the orchestrator
//! can observe, so the run never progresses past "job requested". Instead, every
//! local job runs a small generated shell script (see [`ScriptGenerator`]) whose
//! whole purpose is to report the job's lifecycle back to the orchestrator over
//! gRPC — i.e. to send the "response events" (`JobStarted`, then `JobSucceeded`)
//! a real worker would emit. The orchestrator invokes a local entrypoint as
//!
//! ```text
//! sh -c "<exec> --job-args '<json>'"
//! ```
//!
//! so the script receives the job-run details as a single `--job-args` JSON blob
//! and echoes the relevant ids straight back in its response events.

use std::collections::HashMap;
use std::path::PathBuf;

use rand_chacha::ChaCha8Rng;
use zygo_core::models::{JobEntrypoint, LocalEntrypoint, OrchestratorMode, RemoteEntrypoint};

use crate::generators::{Generate, choose};

/// The `host:port` the orchestrator's gRPC service listens on by default.
///
/// This is the address the harness binds the orchestrator to and the address the
/// generated responder script sends its response events to, so the two must
/// agree. Keeping it here lets both the entrypoint generator and `main` share a
/// single source of truth.
pub const DEFAULT_ORCHESTRATOR_ENDPOINT: &str = "127.0.0.1:50051";

/// File name the responder script is materialized under, inside the OS temp dir.
const RESPONDER_SCRIPT_NAME: &str = "zygo-dst-responder.sh";

/// Absolute path the responder script is installed to (and referenced from by
/// every generated local entrypoint).
///
/// `main` writes [`ScriptGenerator::render`]'s output here before stepping the
/// engine; the generated [`LocalEntrypoint::exec`] points back at it.
pub fn responder_script_path() -> PathBuf {
    std::env::temp_dir().join(RESPONDER_SCRIPT_NAME)
}

/// The body of the responder script, with `__ENDPOINT__` standing in for the
/// orchestrator address. Kept as a template (rather than `format!`) so the
/// shell's own `{`/`}`/`$` syntax does not collide with format placeholders.
const RESPONDER_SCRIPT_TEMPLATE: &str = r#"#!/bin/sh
# Auto-generated by the zygo DST harness (ScriptGenerator).
#
# This is a *local job entrypoint*. The orchestrator runs it as
#     sh -c "<this script> --job-args '<json>'"
# so the job-run details arrive as a single JSON argument. We parse that payload
# and report the job's lifecycle back to the orchestrator over gRPC, which is
# exactly the "response event" flow a real worker would drive.
set -eu

ENDPOINT="__ENDPOINT__"
METHOD="orchestrator.v1.OrchestratorService/HandleEvent"

# Extract the JSON payload that follows the --job-args flag.
JOB_ARGS=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --job-args)
      JOB_ARGS="${2:-}"
      shift 2 || true
      ;;
    *)
      shift
      ;;
  esac
done

if [ -z "$JOB_ARGS" ]; then
  echo "responder: missing --job-args payload" >&2
  exit 1
fi

field() { printf '%s' "$JOB_ARGS" | jq -r ".$1"; }

WORKFLOW_ID=$(field workflow_id)
WORKFLOW_VERSION_ID=$(field workflow_version_id)
RUN_ID=$(field run_id)
JOB_ID=$(field job_id)
JOB_RUN_ID=$(field job_run_id)

new_uuid() {
  if command -v uuidgen >/dev/null 2>&1; then
    uuidgen
  else
    cat /proc/sys/kernel/random/uuid
  fi
}

# Send one JobRunEvent whose `event` oneof is the JSON object passed as $1.
send_event() {
  jq -n \
    --arg id "$(new_uuid)" \
    --arg workflow_id "$WORKFLOW_ID" \
    --arg workflow_version_id "$WORKFLOW_VERSION_ID" \
    --arg run_id "$RUN_ID" \
    --arg job_id "$JOB_ID" \
    --arg job_run_id "$JOB_RUN_ID" \
    --argjson event "$1" \
    '{event: ({
        id: $id,
        runId: {
          workflowId: $workflow_id,
          workflowVersionId: $workflow_version_id,
          workflowRunId: $run_id
        },
        jobRunSource: { jobId: $job_id, jobRunId: $job_run_id }
      } + $event)}' \
    | grpcurl -plaintext -d @ "$ENDPOINT" "$METHOD"
}

send_event '{ "jobStarted": {} }'
send_event '{ "jobSucceeded": {} }'
"#;

/// Generates the shell script a *local* job runs as its entrypoint.
///
/// The script is intentionally generic: it carries no job-specific state and is
/// fully parameterized by the `--job-args` payload the orchestrator passes at
/// run time, so a single materialized script can back every local job in a
/// world. Generation therefore only depends on the orchestrator
/// [`endpoint`](Self::endpoint) the response events should be sent to.
#[derive(Debug, Clone)]
pub struct ScriptGenerator {
    /// `host:port` of the orchestrator gRPC service the script reports to.
    pub endpoint: String,
}

impl Default for ScriptGenerator {
    fn default() -> Self {
        Self {
            endpoint: DEFAULT_ORCHESTRATOR_ENDPOINT.to_owned(),
        }
    }
}

impl ScriptGenerator {
    /// Render the responder script text for this generator's endpoint.
    pub fn render(&self) -> String {
        RESPONDER_SCRIPT_TEMPLATE.replace("__ENDPOINT__", &self.endpoint)
    }
}

impl Generate for ScriptGenerator {
    type Output = String;
    type Context = ();

    /// The script is deterministic in the endpoint alone, so the RNG is unused;
    /// implementing [`Generate`] still lets callers reach it through the same
    /// `generate_seeded`/`generate_value` surface as every other generator.
    fn generate(&self, _rng: &mut ChaCha8Rng, _context: ()) -> String {
        self.render()
    }
}

/// Describes the space of [`JobEntrypoint`]s a job may be given, within a mode.
#[derive(Debug, Clone)]
pub struct EntrypointGenerator {
    /// Working directories a local entrypoint may run in.
    pub working_dirs: Vec<String>,
    /// Absolute path to the responder script every local job executes. Defaults
    /// to [`responder_script_path`]; `main` is responsible for materializing the
    /// script there (see [`ScriptGenerator`]).
    pub script_path: String,
    /// URLs a remote entrypoint may target.
    pub remote_urls: Vec<String>,
}

impl Default for EntrypointGenerator {
    fn default() -> Self {
        Self {
            working_dirs: vec![String::from("/tmp"), String::from("/var/tmp")],
            script_path: responder_script_path().to_string_lossy().into_owned(),
            remote_urls: vec![
                String::from("https://jobs.dst.local/run"),
                String::from("https://jobs.dst.local/exec"),
            ],
        }
    }
}

impl Generate for EntrypointGenerator {
    type Output = JobEntrypoint;
    /// The orchestrator mode the surrounding workflow runs under.
    type Context = OrchestratorMode;

    fn generate(&self, rng: &mut ChaCha8Rng, mode: OrchestratorMode) -> JobEntrypoint {
        match mode {
            OrchestratorMode::Local => JobEntrypoint::Local(LocalEntrypoint {
                cwd: choose(rng, &self.working_dirs).clone(),
                // Run the responder script through `sh` so it needs no execute
                // bit; the orchestrator appends `--job-args '<json>'` for us.
                exec: format!("sh {}", self.script_path),
            }),
            OrchestratorMode::Remote => JobEntrypoint::Remote(RemoteEntrypoint {
                url: choose(rng, &self.remote_urls).clone(),
                headers: HashMap::new(),
            }),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rand::SeedableRng;

    fn rng(seed: u64) -> ChaCha8Rng {
        ChaCha8Rng::seed_from_u64(seed)
    }

    #[test]
    fn local_mode_only_produces_local_entrypoints() {
        let generator = EntrypointGenerator::default();
        for seed in 0..32 {
            let entrypoint = generator.generate(&mut rng(seed), OrchestratorMode::Local);
            assert!(matches!(entrypoint, JobEntrypoint::Local(_)));
        }
    }

    #[test]
    fn remote_mode_only_produces_remote_entrypoints() {
        let generator = EntrypointGenerator::default();
        for seed in 0..32 {
            let entrypoint = generator.generate(&mut rng(seed), OrchestratorMode::Remote);
            assert!(matches!(entrypoint, JobEntrypoint::Remote(_)));
        }
    }

    #[test]
    fn local_entrypoint_runs_the_responder_script() {
        let generator = EntrypointGenerator::default();
        let script_path = responder_script_path();
        let script_path = script_path.to_string_lossy();

        for seed in 0..32 {
            match generator.generate(&mut rng(seed), OrchestratorMode::Local) {
                JobEntrypoint::Local(local) => {
                    assert!(
                        local.exec.contains(script_path.as_ref()),
                        "local exec should invoke the responder script: {}",
                        local.exec
                    );
                }
                JobEntrypoint::Remote(_) => panic!("expected a local entrypoint"),
            }
        }
    }

    #[test]
    fn rendered_script_targets_the_configured_endpoint() {
        let generator = ScriptGenerator {
            endpoint: String::from("10.0.0.1:6000"),
        };
        let script = generator.render();

        assert!(script.contains("10.0.0.1:6000"));
        assert!(!script.contains("__ENDPOINT__"));
        // The two response events a successful job reports back.
        assert!(script.contains("jobStarted"));
        assert!(script.contains("jobSucceeded"));
        assert!(script.contains("orchestrator.v1.OrchestratorService/HandleEvent"));
    }
}
