// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string, title: string) => __TAURI_INVOKE<string>("greet", { name, title }),
	listJobRunSummaries: (request: ListJobRunSummariesRequest) => typedError<ListJobRunSummariesResponse, CommandError>(__TAURI_INVOKE("list_job_run_summaries", { request })),
	listWorkflowRunSummaries: (request: ListWorkflowRunSummariesRequest) => typedError<ListWorkflowRunSummariesResponse, CommandError>(__TAURI_INVOKE("list_workflow_run_summaries", { request })),
	sync: (onEvent: Channel<SyncDelta>) => typedError<null, CommandError>(__TAURI_INVOKE("sync", { onEvent })),
};

/* Types */
/**  The error contract exposed by Tauri commands to the frontend. */
export type CommandError = { kind: "invalid_input"; field: string; message: string } | { kind: "internal"; code: string; message: string };

export type JobRunSummary = {
	id: string,
	workflow_run_id: string,
	job_run_id: string,
	job_id: string,
	status: string,
	duration_ms: number | null,
	retry_count: number,
	created_at: string,
	updated_at: string,
};

export type ListJobRunSummariesRequest = {
	cursor: string | null,
	limit: number,
};

export type ListJobRunSummariesResponse = {
	summaries: JobRunSummary[],
	next_cursor: string | null,
};

export type ListWorkflowRunSummariesRequest = {
	cursor: string | null,
	limit: number,
};

export type ListWorkflowRunSummariesResponse = {
	summaries: WorkflowRunSummary[],
	next_cursor: string | null,
};

export type SyncDelta = { operation: "resync" } | { operation: "delete"; entity: SyncEntityKind; id: string } | { operation: "upsert"; payload: SyncUpsert };

export type SyncEntityKind = "workflow_run_summary" | "job_run_summary";

export type SyncUpsert = { entity: "workflow_run_summary"; id: string; data: WorkflowRunSummary } | { entity: "job_run_summary"; id: string; data: JobRunSummary };

export type WorkflowRunSummary = {
	workflow_run_id: string,
	status: string,
	started_at: number | null,
	completed_at: number | null,
	active_job_count: number,
	succeeded_job_count: number,
	errored_job_count: number,
	created_at: string,
	updated_at: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

