// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string, title: string) => __TAURI_INVOKE<string>("greet", { name, title }),
	loadSyncableData: (request: LoadSyncableDataRequest) => typedError<LoadSyncableDataResponse, CommandError>(__TAURI_INVOKE("load_syncable_data", { request })),
	openSyncChannel: (onEvent: Channel<SyncDelta>, onReady: Channel<null>) => typedError<null, CommandError>(__TAURI_INVOKE("open_sync_channel", { onEvent, onReady })),
	queryLogs: (request: QueryLogsRequest) => typedError<QueryLogsResponse, CommandError>(__TAURI_INVOKE("query_logs", { request })),
	startWorkflowRun: (request: StartWorkflowRunRequest) => typedError<StartWorkflowRunResponse, CommandError>(__TAURI_INVOKE("start_workflow_run", { request })),
};

/* Types */
/**  The error contract exposed by Tauri commands to the frontend. */
export type CommandError = { kind: "invalid_input"; field: string; message: string } | { kind: "internal"; code: string; message: string };

export type JobRun = {
	id: number,
	public_id: string,
	workflow_run_id: number,
	input_id: number,
	job_id: string,
	status: string,
	duration_ms: number | null,
	retry_count: number,
	created_at: string,
};

export type LoadSyncableDataRequest = {
	entity: SyncEntityKind,
	cursor: SyncCursor | null,
	limit: number,
};

export type LoadSyncableDataResponse = { entity: "workflow"; page: SyncPage<Workflow> } | { entity: "workflow_run"; page: SyncPage<WorkflowRun> } | { entity: "job_run"; page: SyncPage<JobRun> } | { entity: "tag"; page: SyncPage<Tag> } | { entity: "data_reference"; page: SyncPage<TauriDataReference> };

export type Log = {
	id: number,
	workflow_run_id: number,
	job_run_id: string,
	content: string,
	created_at: string,
};

export type QueryLogsRequest = {
	workflow_run_id: number,
	limit: number,
	/**  Exclusive lower bound. Present (including 0) pages forward (ASC); absent pages from the newest (DESC). */
	after_id?: number | null,
	/**  Exclusive upper bound for paging older history (DESC). */
	before_id?: number | null,
	/**  Full-text search against log content. Bounds are optional when searching. */
	search?: string | null,
	/**  Filter by job run database id (`job_runs.id`); resolved to the public id for log rows. */
	job_run_id?: number | null,
};

export type QueryLogsResponse = {
	logs: Log[],
	has_more: boolean,
	/**  Global watermark log ID from the same read snapshot as the page. */
	global_watermark_id: number,
};

export type RowChange<T> = { operation: "insert"; row: T } | { operation: "update"; row: T } | { operation: "delete"; id: number };

export type StartWorkflowRunRequest = {
	workflow_id: number,
	input_paths: string[],
	/**  When set, run only this job using a job-scoped schema snapshot. */
	job_id?: string | null,
};

export type StartWorkflowRunResponse = {
	workflow_run_id: number,
	public_id: string,
};

export type SyncCursor = {
	id: number,
};

export type SyncDelta = { entity: "workflow"; change_id: number; change: RowChange<Workflow> } | { entity: "workflow_run"; change_id: number; change: RowChange<WorkflowRun> } | { entity: "job_run"; change_id: number; change: RowChange<JobRun> } | { entity: "tag"; change_id: number; change: RowChange<Tag> } | { entity: "data_reference"; change_id: number; change: RowChange<TauriDataReference> };

export type SyncEntityKind = "workflow" | "workflow_run" | "job_run" | "tag" | "data_reference";

export type SyncPage<T> = {
	next: SyncCursor | null,
	data: T[],
};

export type Tag = {
	id: number,
	workflow_run_id: number,
	job_run_id: number | null,
	data_reference_id: number | null,
	value: string,
	created_at: string,
};

export type TauriDataReference = {
	id: number,
	workflow_run_id: number,
	source_job_run_id: number | null,
	uri: string,
	is_replay: boolean,
	created_at: string,
};

export type Workflow = {
	id: number,
	name: string,
	path: string,
	schema: string,
	created_at: string,
};

export type WorkflowRun = {
	id: number,
	public_id: string,
	workflow_id: number,
	status: string,
	started_at: string | null,
	completed_at: string | null,
	active_job_count: number,
	succeeded_job_count: number,
	errored_job_count: number,
	created_at: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

