/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowWorkflowIdRouteRouteImport } from './routes/workflow.$workflowId/route'
import { Route as WorkflowWorkflowIdIndexRouteImport } from './routes/workflow.$workflowId/index'
import { Route as WorkflowWorkflowIdRunIdRouteImport } from './routes/workflow.$workflowId/$runId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowWorkflowIdRouteRoute = WorkflowWorkflowIdRouteRouteImport.update({
  id: '/workflow/$workflowId',
  path: '/workflow/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowWorkflowIdIndexRoute = WorkflowWorkflowIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowWorkflowIdRouteRoute,
} as any)
const WorkflowWorkflowIdRunIdRoute = WorkflowWorkflowIdRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => WorkflowWorkflowIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/workflow/$workflowId': typeof WorkflowWorkflowIdRouteRouteWithChildren
  '/workflow/$workflowId/$runId': typeof WorkflowWorkflowIdRunIdRoute
  '/workflow/$workflowId/': typeof WorkflowWorkflowIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/workflow/$workflowId/$runId': typeof WorkflowWorkflowIdRunIdRoute
  '/workflow/$workflowId': typeof WorkflowWorkflowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/workflow/$workflowId': typeof WorkflowWorkflowIdRouteRouteWithChildren
  '/workflow/$workflowId/$runId': typeof WorkflowWorkflowIdRunIdRoute
  '/workflow/$workflowId/': typeof WorkflowWorkflowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/workflow/$workflowId'
    | '/workflow/$workflowId/$runId'
    | '/workflow/$workflowId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/workflow/$workflowId/$runId'
    | '/workflow/$workflowId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/workflow/$workflowId'
    | '/workflow/$workflowId/$runId'
    | '/workflow/$workflowId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  WorkflowWorkflowIdRouteRoute: typeof WorkflowWorkflowIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$workflowId': {
      id: '/workflow/$workflowId'
      path: '/workflow/$workflowId'
      fullPath: '/workflow/$workflowId'
      preLoaderRoute: typeof WorkflowWorkflowIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$workflowId/': {
      id: '/workflow/$workflowId/'
      path: '/'
      fullPath: '/workflow/$workflowId/'
      preLoaderRoute: typeof WorkflowWorkflowIdIndexRouteImport
      parentRoute: typeof WorkflowWorkflowIdRouteRoute
    }
    '/workflow/$workflowId/$runId': {
      id: '/workflow/$workflowId/$runId'
      path: '/$runId'
      fullPath: '/workflow/$workflowId/$runId'
      preLoaderRoute: typeof WorkflowWorkflowIdRunIdRouteImport
      parentRoute: typeof WorkflowWorkflowIdRouteRoute
    }
  }
}

interface WorkflowWorkflowIdRouteRouteChildren {
  WorkflowWorkflowIdRunIdRoute: typeof WorkflowWorkflowIdRunIdRoute
  WorkflowWorkflowIdIndexRoute: typeof WorkflowWorkflowIdIndexRoute
}

const WorkflowWorkflowIdRouteRouteChildren: WorkflowWorkflowIdRouteRouteChildren =
  {
    WorkflowWorkflowIdRunIdRoute: WorkflowWorkflowIdRunIdRoute,
    WorkflowWorkflowIdIndexRoute: WorkflowWorkflowIdIndexRoute,
  }

const WorkflowWorkflowIdRouteRouteWithChildren =
  WorkflowWorkflowIdRouteRoute._addFileChildren(
    WorkflowWorkflowIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  WorkflowWorkflowIdRouteRoute: WorkflowWorkflowIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
