/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as RunsWorkflowRunIdRouteImport } from './routes/runs/$workflowRunId'
import { Route as RunsWorkflowRunIdJobsJobIdRouteImport } from './routes/runs/$workflowRunId/jobs/$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsWorkflowRunIdRoute = RunsWorkflowRunIdRouteImport.update({
  id: '/$workflowRunId',
  path: '/$workflowRunId',
  getParentRoute: () => RunsRoute,
} as any)
const RunsWorkflowRunIdJobsJobIdRoute =
  RunsWorkflowRunIdJobsJobIdRouteImport.update({
    id: '/jobs/$jobId',
    path: '/jobs/$jobId',
    getParentRoute: () => RunsWorkflowRunIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/runs': typeof RunsRouteWithChildren
  '/runs/$workflowRunId': typeof RunsWorkflowRunIdRouteWithChildren
  '/runs/$workflowRunId/jobs/$jobId': typeof RunsWorkflowRunIdJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/runs': typeof RunsRouteWithChildren
  '/runs/$workflowRunId': typeof RunsWorkflowRunIdRouteWithChildren
  '/runs/$workflowRunId/jobs/$jobId': typeof RunsWorkflowRunIdJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/runs': typeof RunsRouteWithChildren
  '/runs/$workflowRunId': typeof RunsWorkflowRunIdRouteWithChildren
  '/runs/$workflowRunId/jobs/$jobId': typeof RunsWorkflowRunIdJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/runs' | '/runs/$workflowRunId' | '/runs/$workflowRunId/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/runs' | '/runs/$workflowRunId' | '/runs/$workflowRunId/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/runs'
    | '/runs/$workflowRunId'
    | '/runs/$workflowRunId/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RunsRoute: typeof RunsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$workflowRunId': {
      id: '/runs/$workflowRunId'
      path: '/$workflowRunId'
      fullPath: '/runs/$workflowRunId'
      preLoaderRoute: typeof RunsWorkflowRunIdRouteImport
      parentRoute: typeof RunsRoute
    }
    '/runs/$workflowRunId/jobs/$jobId': {
      id: '/runs/$workflowRunId/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/runs/$workflowRunId/jobs/$jobId'
      preLoaderRoute: typeof RunsWorkflowRunIdJobsJobIdRouteImport
      parentRoute: typeof RunsWorkflowRunIdRoute
    }
  }
}

interface RunsWorkflowRunIdRouteChildren {
  RunsWorkflowRunIdJobsJobIdRoute: typeof RunsWorkflowRunIdJobsJobIdRoute
}

const RunsWorkflowRunIdRouteChildren: RunsWorkflowRunIdRouteChildren = {
  RunsWorkflowRunIdJobsJobIdRoute: RunsWorkflowRunIdJobsJobIdRoute,
}

const RunsWorkflowRunIdRouteWithChildren =
  RunsWorkflowRunIdRoute._addFileChildren(RunsWorkflowRunIdRouteChildren)

interface RunsRouteChildren {
  RunsWorkflowRunIdRoute: typeof RunsWorkflowRunIdRouteWithChildren
}

const RunsRouteChildren: RunsRouteChildren = {
  RunsWorkflowRunIdRoute: RunsWorkflowRunIdRouteWithChildren,
}

const RunsRouteWithChildren = RunsRoute._addFileChildren(RunsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RunsRoute: RunsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
