[package]
name = "desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
gpui = { package = "gpui-unofficial", version = "=1.14.2" }
gpui_platform = { package = "gpui-platform-gpui-unofficial", version = "=1.14.2" }
local = { path = "../local" }
zygo-core = { path = "../core" }
anyhow = { workspace = true }
gpuikit = "=0.7.0"

[dev-dependencies]
gpui = { package = "gpui-unofficial", version = "=1.14.2", features = ["test-support"] }
