# List available recipes
default:
    @just --list

dev:
    pnpm tauri dev

lint:
    oxlint

fmt:
    oxfmt

typecheck:
    pnpm tsc

# Generate TypeScript bindings from Rust code
generate-bindings:
    cargo run \
    --manifest-path src-tauri/Cargo.toml \
    --features codegen \
    --bin generate-bindings
