# List available recipes
default:
    @just --list

dev:
    pnpm tauri dev

typecheck:
    pnpm tsc

lint:
    pnpm exec oxlint

lint-fix:
    pnpm exec oxlint --fix --fix-suggestions

stylelint:
    pnpm exec stylelint "src/**/*.{css,scss}"

fmt:
    pnpm exec oxfmt

# Run all checks/lints/etc available
check: lint stylelint typecheck

# Apply available autofixes
fix: fmt lint-fix

test:
    pnpm test

# Generate TypeScript bindings from Rust code
generate-bindings:
    cargo run \
    --manifest-path src-tauri/Cargo.toml \
    --features codegen \
    --bin generate-bindings
